eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8904
spring:
  application:
    name: service-zuul

zuul:
  routes:
    feign:
      path: /api-feign/**
      serviceId: service-feign
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 3000
